### ISSUE TITLE
UERANSIM gNB unable to communicate with Free5GMANO AMF

### ISSUE THREAD

**Issue by ananay** [free5gmano/free5gmano#90]
My UERANSIM is not able to communicate with my AMF. The UERANSIM gNB just gets stuck at: “Trying to establish SCTP connection… (10.244.0.192:29518)”
and is never able to connect.

    I’m using kubernetes v1.15.3
    AMF is “Listen on 10.244.0.142:38412”
    UERANSIM is stuck on “Trying to establish SCTP connection… (10.244.0.142:38412)”
    UERANSIM version is “v3.1.0”
    netstat --sctp -tulpn on the AMF container shows that the AMF is listening on 38412.
    I have tested using ncat to make a test server that SCTP protocol is working over my Kube container

Please help me! I am unable to figure out a solution as to why this is not working!
Please let me know if any additional information is needed. Any help would be greatly appreciated!

**Comment by j13tw** [comment]
Hello @ananay 
If you use the kubernetes before v1.19
The AMF SCTP(NGAP) communicate are not default enable.
Maybe you can check your ```free5gc-amf-svc``` create or not?
Here is the Kubernetes Official Doc to Enable the SCTP communicate in cluster
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

```
/etc/kubernetes/manifests/kube-apiserver.yaml
---
spec:
  containers:
  - command:
  ...
    - --feature-gates=SCTPSupport=true
  ...
```

By the way,
In Kubernetes v1.19 later, 
The SCTP communicate are default enable.

**Comment by ananay** [comment]
Hi, it still won't communicate over SCTP - UERANSIM always times out.

**Comment by j13tw** [comment]
Hello, @ananay 
ueransim-configmap.yaml on gnb pod has four ip address must be modify
```
    linkIp: 127.0.0.1                # The gnb pod ip for UE link,  encapsulate and encapsulate between UDP and GTP-U
    ngapIp: 127.0.0.1             # The gnb pod ip to link AMF to Send and Receive NGAP/NAS
    gtpIp: 127.0.0.1                 # The gnb pod ip to link UPF to Send and Receive GTP-U 
    # List of AMF address information
    amfConfigs:
      - address: 127.0.0.1.      # Setup the AMF NGAP  IP List Info, the IP is the AMF Reevice SCTP(NGAP)
        port: 38412
```

I think you should check the NGAP Serving which IP are used on AMF Config
the free5gmano has free5gc yaml file to testing, and it can used the nmctl to deploy free5gc.
If you used the yaml file to deploy, the free5gmano provide the OVS dual NIC and k8s Service Mode

In free5gmano deploy free5gc on dual NIC Mode
the AMF ngapIpList is based on the OVS-Switch bridge port Interface IP (IP Range: 192.168.2.xx/23)
So  UERANSIM gnb also need to create the Interface to connected the AMF
and gnb Config ```gnbIp``` need setup the OVS bridge port Interface  IP

```
  amfcfg.conf: |
    info:
      version: 1.0.0
      description: AMF initial local configuration
    configuration:
      amfName: AMF
      ngapIpList:
        - 192.168.2.162
```

In the k8s CNI Mode
the AMF ngapIpList is based on the k8s service 
and setup the AMF service with ```clusterIP:  None```` to resolve the AMF Pod IP
the UERANSIM gnb can used the AMF Pod IP to connect NGAP between gnb and AMF
and gnb Config ```gnbIp``` need setup the Pod IP

```
  amfcfg.conf: |
    info:
      version: 1.0.0
      description: AMF initial local configuration
    configuration:
      amfName: AMF
      ngapIpList:
        - free5gc-amf-svc
```

So, If you Setup the OVS bridge port interface IP on AMF ngapIpList
the UERANSIM gnb SCTP cannot used the AMF Pod IP access the NGAP service.
